export const PICK_DESTINATION = 'helios/App/PICK_DESTINATION';
export const PICK_DESTINATION_SUCCESS = "helios/App/PICK_DESTINATION_SUCCESS";
export const PICK_DESTINATION_ERROR = "helios/App/PICK_DESTINATION_ERROR";