

const weatherConditionMap = {
	0: "sunny weather",
	1: "partly cloudy weather",
	2: "cloudy weather",
	3: "overcast weather",
	10: "partly cloudy weather",
	20: "cloudy weather",
	30: "overcast weather",
	4: "foggy weather",
	40: "foggy weather",
	45: "foggy weather",
	48: "freezing foggy weather",
	49: "freezing foggy weather",
	5: "drizzly weather",
	50: "drizzly weather",
	51: "light drizzly weather",
	53: "drizzly weather",
	55: "heavy drizzly weather",
	56: "light freezing drizzly weather",
	57: "intense freezing drizzly weather",
	6: "rainy weather",
	60: "light rain",
	61: "light rain",
	63: "modest rain",
	65: "heavy rain",
	66: "light freezing rain",
	67: "modest freezing rain",
	68: "light rain snow",
	69: "heavy rain snow",
	7: "snow",
	70: "light snow",
	71: "light snow",
	73: "modest snow",
	75: "heavy snow",
	8: "showers",
	80: "light rain showers",
	81: "rain showers",
	82: "heavy rain showers",
	83: "light showers",
	84: "heavy showers",
	85: "light snowy showers",
	86: "heavy snowy showers",
	9: "thunderstorms",
	90: "thunderstorms",
	95: "light thunderstorms",
	96: "heavy thunderstorms",
	999: "uninteresting weather"
}

export const mapWeatherCondition = (weatherConditionId) => weatherConditionMap[weatherConditionId]
